name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pip
          cache-dependency-path: |
            requirements.txt
            tools/requirements.txt
      - name: Install dependencies
        run: pip install -r tools/requirements.txt -r requirements.txt
      - name: Change permissions
        run: chmod 755 docs
      - name: Detect docs changes
        id: docs_changes
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            if git diff --quiet HEAD^ HEAD -- docs; then
              echo "changed=false" >> "$GITHUB_OUTPUT"
            else
              echo "changed=true" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Auto-i18n_translate
        if: steps.docs_changes.outputs.changed == 'true'
        env:
          # 设置环境变量
          ### API BASE:
          #CHATGPT_API_BASE: ${{ secrets.CHATGPT_API_BASE }}
          CHATGPT_API_BASE: ${{ secrets.URL_CHATANYWHERE }}
          #CHATGPT_API_BASE: ${{ secrets.URL_OPENAI_FAKE }}
          #CHATGPT_API_BASE: ${{ secrets.URL_OPENAI }}
          ### API KEY:
          #CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
          #CHATGPT_API_KEY: ${{ secrets.KEY_CHATANYWHERE_IRIS }}
          CHATGPT_API_KEY: ${{ secrets.KEY_CHATANYWHERE_ME }}
          #CHATGPT_API_KEY: ${{ secrets.KEY_OPENAI_FAKE_LINYUXUANLIN52 }}
          #CHATGPT_API_KEY: ${{ secrets.KEY_OPENAI_FAKE_LISU }} #x
          #CHATGPT_API_KEY: ${{ secrets.KEY_OPENAI_LINYUXUANLIN52 }}
        run: |
          python tools/auto-translater.py || true
      - name: Commit translated
        run: |
          git config --global user.email 824676271@qq.com
          git config --global user.name linyuxuanlin
          git add .
          git commit -m "Commit translated" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy with MkDocs
        run: mkdocs gh-deploy --force